---
title: "MacWhinney Symposium Workshops"
author: "Rick O. Gilmore"
date: "`r Sys.time()`"
output: 
  html_document:
    toc: true
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,  message = FALSE, warning = FALSE)
```

## Purpose

This document facilitates the management of registrations at the workshops slated for Thursday, June 6, 2019.

It depends on the `googlesheets` package, documented here: <https://cran.r-project.org/web/packages/googlesheets/vignettes/basic-usage.html>

```{r}
library(googlesheets)
library(tidyverse)
```

```{r}
# Download registrations from Google sheet

ws_url <- "https://docs.google.com/forms/d/1tN5qri9YV6JjLO4nNoG6OmtTFl78NxBl941SlhKTqhI"
ws_name <- "Symposium In Honor of Brian MacWhinney (Responses)"
ws_key <- "1tN5qri9YV6JjLO4nNoG6OmtTFl78NxBl941SlhKTqhI/"

mw <- googlesheets::gs_title(ws_name)

workshops <- mw %>%
  googlesheets::gs_read(ws = 'Workshop Registration') %>%
  rename(Attend = 'Check the workshops you are interested in attending')

# symp <- mw %>%
#   gs_read(ws = 'Symposium Registration')
```

## AphasiaBank workshop

```{r}
workshops %>%
  filter(., str_detect(Attend, "AphasiaBank")) %>%
  select(., Name, Institution) %>%
  knitr::kable(.)
```


## PhonBank workshop

```{r}
workshops %>%
  filter(., str_detect(Attend, "PhonBank")) %>%
  select(., Name, Institution) %>%
  knitr::kable(.)
```

## TalkBankDB workshop

```{r}
workshops %>%
  filter(., str_detect(Attend, "TalkBankDB")) %>%
  select(., Name, Institution) %>%
  knitr::kable(.)
```

## Databrary workshop

```{r}
workshops %>%
  filter(., str_detect(Attend, "Data[bB]")) %>%
  select(., Name, Institution) %>%
  knitr::kable(.)
```

